### ISSUE TITLE
Issue in Release build 

### ISSUE THREAD

**Issue by Resham143** [curtisshipley/BlueMonkey#1]
I have tested the libraries in debug mode and are working fine but when I create a release build It is not working. the survey page did not display.Is it is only for debug mode.

**Comment by curtisshipley** [comment]
It looks like Xamarin/Android doesn't include x86 as a target. I just checked in a fix. Let me know if that works for Android. (I assume that is what you meant).

**Comment by Resham143** [comment]
No this issue occurs in case of iOS release build only . Android is working fine.

**Comment by curtisshipley** [comment]
Odd, looks like the main storyboard got moved into the Android project. Try it now.
